version: '3.3'

services:
  app: hw26
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    ports:
      - "5434:5432"